# Generated by Django 5.0.1 on 2024-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
