# Generated by Django 5.0.1 on 2024-01-10 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("due", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.PositiveIntegerField(
                        choices=[(0, "EEI"), (1, "RC"), (10, "OTHERS")]
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requirements.requirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "requirement",
                "verbose_name_plural": "requirements",
            },
        ),
        migrations.CreateModel(
            name="Compliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                (
                    "point_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.requirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "compliance",
                "verbose_name_plural": "compliances",
            },
        ),
    ]
