# Generated by Django 5.0.1 on 2024-01-10 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="submission_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
