# Generated by Django 5.0.1 on 2024-01-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirement_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='control_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Control Number'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='control_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Control Number'),
        ),
    ]
